name: Node.js Test Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    - run: npm ci
    - run: npm run lint
    - run: npm run format
    - run: npm run build:dev
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }} 
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
    - name: Deploy with rsync
      run: rsync -avzhe ssh dist/* ${{ secrets.SSH_TEST_USER }}@${{ secrets.SSH_TEST_HOST }}:/var/www/html

  